// Kashmir Essence — PSEO product axis (India + Global matrices)
// Slugs are PERMANENT. Never rename.

export const kashmirProducts = [
  { slug: "saffron",       name: "Kashmiri Saffron",    certification: "GI-Tagged · ISO 3632 Cat. I", origin: "Pampore, Kashmir",          productSlug: "kashmiri-saffron-mongra"    },
  { slug: "mamra-almonds", name: "Mamra Almonds",        certification: "Heritage Kashmir Variety",    origin: "Karewa Highlands, Kashmir",  productSlug: "mamra-almonds-premium"      },
  { slug: "walnuts",       name: "Kashmiri Walnuts",     certification: "Kashmir Valley Grown",        origin: "Wular Basin, Kashmir",       productSlug: "kashmiri-walnut-kernels"    },
  { slug: "honey",         name: "Kashmir Honey",        certification: "Raw · Cold-Extracted",        origin: "Alpine Meadows, Kashmir",    productSlug: "kashmiri-wildflower-honey"  },
  { slug: "kahwa",         name: "Kashmiri Kahwa",       certification: "Authentic Valley Blend",      origin: "Kashmir Valley",             productSlug: "kashmiri-kahwa-blend"       },
  { slug: "chilli",        name: "Kashmiri Chilli",      certification: "Kashmir Valley Grown",        origin: "Srinagar District, Kashmir", productSlug: "kashmiri-chilli-powder"     },
  { slug: "dry-fruits",    name: "Kashmir Dry Fruits",   certification: "Direct from Valley",          origin: "Kashmir Valley",             productSlug: "kashmiri-dry-fruit-gift-box"},
  { slug: "saffron-gift",  name: "Kashmir Saffron Gift", certification: "GI-Tagged · Premium Gift",   origin: "Pampore, Kashmir",           productSlug: "kashmiri-saffron-gift-tin"  },
  { slug: "shilajit",      name: "Himalayan Shilajit",   certification: "Lab Tested · Fulvic Acid Verified", origin: "High Himalayas, J&K",    productSlug: "himalayan-shilajit-resin"   },
];

export type KashmirProduct = (typeof kashmirProducts)[0];

// ── INDIA CITIES (134) ──────────────────────────────────────────────────────
export const cities = [
  { slug: "mumbai",         name: "Mumbai",         state: "Maharashtra" },
  { slug: "delhi-ncr",      name: "Delhi NCR",      state: "Delhi" },
  { slug: "bangalore",      name: "Bangalore",      state: "Karnataka" },
  { slug: "pune",           name: "Pune",           state: "Maharashtra" },
  { slug: "hyderabad",      name: "Hyderabad",      state: "Telangana" },
  { slug: "chennai",        name: "Chennai",        state: "Tamil Nadu" },
  { slug: "kolkata",        name: "Kolkata",        state: "West Bengal" },
  { slug: "ahmedabad",      name: "Ahmedabad",      state: "Gujarat" },
  { slug: "surat",          name: "Surat",          state: "Gujarat" },
  { slug: "jaipur",         name: "Jaipur",         state: "Rajasthan" },
  { slug: "nagpur",         name: "Nagpur",         state: "Maharashtra" },
  { slug: "nashik",         name: "Nashik",         state: "Maharashtra" },
  { slug: "indore",         name: "Indore",         state: "Madhya Pradesh" },
  { slug: "chandigarh",     name: "Chandigarh",     state: "Punjab" },
  { slug: "lucknow",        name: "Lucknow",        state: "Uttar Pradesh" },
  { slug: "kochi",          name: "Kochi",          state: "Kerala" },
  { slug: "coimbatore",     name: "Coimbatore",     state: "Tamil Nadu" },
  { slug: "vijayawada",     name: "Vijayawada",     state: "Andhra Pradesh" },
  { slug: "goa",            name: "Goa",            state: "Goa" },
  { slug: "mangalore",      name: "Mangalore",      state: "Karnataka" },
  { slug: "mysore",         name: "Mysore",         state: "Karnataka" },
  { slug: "aurangabad",     name: "Aurangabad",     state: "Maharashtra" },
  { slug: "kolhapur",       name: "Kolhapur",       state: "Maharashtra" },
  { slug: "navi-mumbai",    name: "Navi Mumbai",    state: "Maharashtra" },
  { slug: "thane",          name: "Thane",          state: "Maharashtra" },
  { slug: "noida",          name: "Noida",          state: "Uttar Pradesh" },
  { slug: "gurgaon",        name: "Gurgaon",        state: "Haryana" },
  { slug: "vadodara",       name: "Vadodara",       state: "Gujarat" },
  { slug: "bhopal",         name: "Bhopal",         state: "Madhya Pradesh" },
  { slug: "visakhapatnam",  name: "Visakhapatnam",  state: "Andhra Pradesh" },
  { slug: "patna",          name: "Patna",          state: "Bihar" },
  { slug: "kanpur",         name: "Kanpur",         state: "Uttar Pradesh" },
  { slug: "raipur",         name: "Raipur",         state: "Chhattisgarh" },
  { slug: "ranchi",         name: "Ranchi",         state: "Jharkhand" },
  { slug: "bhubaneswar",    name: "Bhubaneswar",    state: "Odisha" },
  { slug: "guwahati",       name: "Guwahati",       state: "Assam" },
  { slug: "dehradun",       name: "Dehradun",       state: "Uttarakhand" },
  { slug: "ludhiana",       name: "Ludhiana",       state: "Punjab" },
  { slug: "amritsar",       name: "Amritsar",       state: "Punjab" },
  { slug: "jodhpur",        name: "Jodhpur",        state: "Rajasthan" },
  { slug: "udaipur",        name: "Udaipur",        state: "Rajasthan" },
  { slug: "kota",           name: "Kota",           state: "Rajasthan" },
  { slug: "bikaner",        name: "Bikaner",        state: "Rajasthan" },
  { slug: "ajmer",          name: "Ajmer",          state: "Rajasthan" },
  { slug: "jabalpur",       name: "Jabalpur",       state: "Madhya Pradesh" },
  { slug: "gwalior",        name: "Gwalior",        state: "Madhya Pradesh" },
  { slug: "ujjain",         name: "Ujjain",         state: "Madhya Pradesh" },
  { slug: "jhansi",         name: "Jhansi",         state: "Uttar Pradesh" },
  { slug: "meerut",         name: "Meerut",         state: "Uttar Pradesh" },
  { slug: "agra",           name: "Agra",           state: "Uttar Pradesh" },
  { slug: "varanasi",       name: "Varanasi",       state: "Uttar Pradesh" },
  { slug: "prayagraj",      name: "Prayagraj",      state: "Uttar Pradesh" },
  { slug: "bareilly",       name: "Bareilly",       state: "Uttar Pradesh" },
  { slug: "aligarh",        name: "Aligarh",        state: "Uttar Pradesh" },
  { slug: "moradabad",      name: "Moradabad",      state: "Uttar Pradesh" },
  { slug: "saharanpur",     name: "Saharanpur",     state: "Uttar Pradesh" },
  { slug: "gorakhpur",      name: "Gorakhpur",      state: "Uttar Pradesh" },
  { slug: "jalandhar",      name: "Jalandhar",      state: "Punjab" },
  { slug: "patiala",        name: "Patiala",        state: "Punjab" },
  { slug: "bathinda",       name: "Bathinda",       state: "Punjab" },
  { slug: "rohtak",         name: "Rohtak",         state: "Haryana" },
  { slug: "panipat",        name: "Panipat",        state: "Haryana" },
  { slug: "karnal",         name: "Karnal",         state: "Haryana" },
  { slug: "shimla",         name: "Shimla",         state: "Himachal Pradesh" },
  { slug: "jammu",          name: "Jammu",          state: "Jammu and Kashmir" },
  { slug: "srinagar",       name: "Srinagar",       state: "Jammu and Kashmir" },
  { slug: "siliguri",       name: "Siliguri",       state: "West Bengal" },
  { slug: "agartala",       name: "Agartala",       state: "Tripura" },
  { slug: "shillong",       name: "Shillong",       state: "Meghalaya" },
  { slug: "imphal",         name: "Imphal",         state: "Manipur" },
  { slug: "kohima",         name: "Kohima",         state: "Nagaland" },
  { slug: "aizawl",         name: "Aizawl",         state: "Mizoram" },
  { slug: "gangtok",        name: "Gangtok",        state: "Sikkim" },
  { slug: "itanagar",       name: "Itanagar",       state: "Arunachal Pradesh" },
  { slug: "panaji",         name: "Panaji",         state: "Goa" },
  { slug: "calicut",        name: "Calicut",        state: "Kerala" },
  { slug: "thrissur",       name: "Thrissur",       state: "Kerala" },
  { slug: "trivandrum",     name: "Trivandrum",     state: "Kerala" },
  { slug: "salem",          name: "Salem",          state: "Tamil Nadu" },
  { slug: "madurai",        name: "Madurai",        state: "Tamil Nadu" },
  { slug: "tiruchirappalli",name: "Tiruchirappalli",state: "Tamil Nadu" },
  { slug: "tirunelveli",    name: "Tirunelveli",    state: "Tamil Nadu" },
  { slug: "vellore",        name: "Vellore",        state: "Tamil Nadu" },
  { slug: "warangal",       name: "Warangal",       state: "Telangana" },
  { slug: "guntur",         name: "Guntur",         state: "Andhra Pradesh" },
  { slug: "tirupati",       name: "Tirupati",       state: "Andhra Pradesh" },
  { slug: "nellore",        name: "Nellore",        state: "Andhra Pradesh" },
  { slug: "kakinada",       name: "Kakinada",       state: "Andhra Pradesh" },
  { slug: "rajahmundry",    name: "Rajahmundry",    state: "Andhra Pradesh" },
  { slug: "belgaum",        name: "Belgaum",        state: "Karnataka" },
  { slug: "hubli",          name: "Hubli",          state: "Karnataka" },
  { slug: "dharwad",        name: "Dharwad",        state: "Karnataka" },
  { slug: "gulbarga",       name: "Gulbarga",       state: "Karnataka" },
  { slug: "bellary",        name: "Bellary",        state: "Karnataka" },
  { slug: "shimoga",        name: "Shimoga",        state: "Karnataka" },
  { slug: "tumkur",         name: "Tumkur",         state: "Karnataka" },
  { slug: "hosur",          name: "Hosur",          state: "Tamil Nadu" },
  { slug: "erode",          name: "Erode",          state: "Tamil Nadu" },
  { slug: "tiruppur",       name: "Tiruppur",       state: "Tamil Nadu" },
  { slug: "thanjavur",      name: "Thanjavur",      state: "Tamil Nadu" },
  { slug: "asansol",        name: "Asansol",        state: "West Bengal" },
  { slug: "durgapur",       name: "Durgapur",       state: "West Bengal" },
  { slug: "howrah",         name: "Howrah",         state: "West Bengal" },
  { slug: "kharagpur",      name: "Kharagpur",      state: "West Bengal" },
  { slug: "dhanbad",        name: "Dhanbad",        state: "Jharkhand" },
  { slug: "bokaro",         name: "Bokaro",         state: "Jharkhand" },
  { slug: "jamshedpur",     name: "Jamshedpur",     state: "Jharkhand" },
  { slug: "bilaspur",       name: "Bilaspur",       state: "Chhattisgarh" },
  { slug: "bhilai",         name: "Bhilai",         state: "Chhattisgarh" },
  { slug: "korba",          name: "Korba",          state: "Chhattisgarh" },
  { slug: "jamnagar",       name: "Jamnagar",       state: "Gujarat" },
  { slug: "rajkot",         name: "Rajkot",         state: "Gujarat" },
  { slug: "bhavnagar",      name: "Bhavnagar",      state: "Gujarat" },
  { slug: "junagadh",       name: "Junagadh",       state: "Gujarat" },
  { slug: "gandhinagar",    name: "Gandhinagar",    state: "Gujarat" },
  { slug: "amravati",       name: "Amravati",       state: "Maharashtra" },
  { slug: "akola",          name: "Akola",          state: "Maharashtra" },
  { slug: "latur",          name: "Latur",          state: "Maharashtra" },
  { slug: "solapur",        name: "Solapur",        state: "Maharashtra" },
  { slug: "nanded",         name: "Nanded",         state: "Maharashtra" },
  { slug: "sangli",         name: "Sangli",         state: "Maharashtra" },
  { slug: "jalgaon",        name: "Jalgaon",        state: "Maharashtra" },
  { slug: "ahmednagar",     name: "Ahmednagar",     state: "Maharashtra" },
  { slug: "dhule",          name: "Dhule",          state: "Maharashtra" },
  { slug: "chandrapur",     name: "Chandrapur",     state: "Maharashtra" },
  { slug: "parbhani",       name: "Parbhani",       state: "Maharashtra" },
  { slug: "ichalkaranji",   name: "Ichalkaranji",   state: "Maharashtra" },
];

export type City = (typeof cities)[0];
